version: '3'
services:
  discovery:
    image: delivery/discovery:latest
    ports:
      - "8761:8761"
    restart: always

  auth-service:
    image: delivery/auth-service:latest
    ports:
      - "8083:8083"
    environment:
      - CONFIG_URI=http://discovery:8761
      - EUREKA_URI=http://discovery:8761/eureka
      - DATABASE_URL=jdbc:postgresql://psql:5432/auth_user_db
      - DATABASE_USER=postgre_user
      - DATABASE_PASSWORD=postgre_secret_password
    restart: always
    depends_on:
      - discovery

  order-service:
    image: delivery/order-service:latest
    ports:
      - "8080:8080"
    environment:
      - CONFIG_URI=http://discovery:8761
      - EUREKA_URI=http://discovery:8761/eureka
      - DATABASE_URL=jdbc:postgresql://psql:5432/order_db
      - DATABASE_USER=postgre_user
      - DATABASE_PASSWORD=postgre_secret_password
    restart: always
    depends_on:
      - discovery

  payment-service:
    image: delivery/payment-service:latest
    ports:
      - "8081:8081"
    environment:
      - CONFIG_URI=http://discovery:8761
      - EUREKA_URI=http://discovery:8761/eureka
      - DATABASE_URL=jdbc:postgresql://psql:5432/payment_db
      - DATABASE_USER=postgre_user
      - DATABASE_PASSWORD=postgre_secret_password
    restart: always
    depends_on:
      - discovery


  gateway:
    image: delivery/gateway:latest
    ports:
      - "9090:9090"
    environment:
      - CONFIG_URI=http://discovery:8761
      - EUREKA_URI=http://discovery:8761/eureka
    restart: always
    depends_on:
      - discovery
      - auth-service
      - order-service
      - payment-service
