scrape_configs:
  - job_name: 'auth-service_monitoring'
    scrape_interval: 15s
    metrics_path: '/auth/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'order-service_monitoring'
    scrape_interval: 15s
    metrics_path: '/api/order/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'payment-service_monitoring'
    scrape_interval: 15s
    metrics_path: '/api/payment/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'inventory-service_monitoring'
    scrape_interval: 15s
    metrics_path: '/api/inventory/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'delivery-service_monitoring'
    scrape_interval: 15s
    metrics_path: '/api/delivery/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: 'gateway_monitoring'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']